spring:
	application:
		name: Education-Tracking-System

#DataBase Configuration
	datasource:
		url: jdbc:mysql://localhost:3306/education_tracking_db?createDatabaseIfNotExist=true
		username: root
		password: root
		
	jpa:
		hibernate:
			ddl-auto: update
			
		properties:
			hibernate:
				format_sql: true
				
		show-sql: true

#Application Properties
super_admin:
	email: ${super-admin.email}